version: '3.8'

services:
  app:
    build:
      context: .
      tty: true  
    working_dir: /app
    command: python script.py
    volumes:
      - ./app:/app
      - ./credentials:/app/credentials
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=scraped_data
    volumes:
      - dev-db:/var/lib/postgresql/data

volumes:
  dev-db:
